### ISSUE TITLE
Multiple Itach Devices

### ISSUE THREAD

**Issue by DaronLord** [dustindclark/homebridge-globalcache-itach#3]
Dustin

Thank you for the quick response and terrific effort.  I just realized that the recent version has an error.  The plugin technically works.  But, in the current version whether you configure 1 or multiple Itach devices the plugin starts successfully but you loss the ability in HomeKit via Siri to address/request an entire room to be turned on/off.  With the plugin enabled Siri believes that no devices are located in any room.  I verified that if I remove the plugin from the config.json that you are again able to address a room. For instance with the plugin enabled you can't say "Turn off the Lights in Room 2."  Siri responds, "There are no devices in Room 2."  As soon is the plugin is disabled the ability returns.  

I noticed in the code that you made the following change registering each device as a platform instead of an accessory:

```
homebridge.registerPlatform("homebridge-globalcache-itach", "GlobalCacheItach", ItachPlatform);
//homebridge.registerAccessory("homebridge-globalcache-itach", "GlobalCacheItach", ItachAccessory);
```

This appears to have caused the issue.  In the interim could you reverse the change so that I can continue to use one device successfully.  I didn't make it to UPS today but I will be overnighting you the device in the morning for you testing.  Thanks for everything, not pressure on getting multiple devices to work take your time and just let me know when you have nailed it.  I realize we all have day jobs.  ;-)

Thanks in advance,

Daron

**Comment by dustindclark** [comment]
@DaronLord, that wouldn't be the culprit because that change was in place from the beginning (here's the 0.1 tag: https://github.com/dustindclark/homebridge-globalcache-itach/blob/0.1/index.js).  Using a platform instead of an accessory allows detecting multiple accessories for a given device (i.e. the 3 IR and/or relay ports).  Let me do some testing and I'll get back to you.

**Comment by dustindclark** [comment]
@DaronLord , can you try 0.1.5?  I think adding support for more than just "on" and "off" commands breaks this because there's more than one switch created for each device.  I've fixed a problem where the on/off commands were being duplicated though, so it will work if you only have "on" and "off" defined on each port.  Let me know.  Thanks.

**Comment by dustindclark** [comment]
Standby...there's now a bug with that version too if you send multiple commands for on and off.  I'm working on a fix.

**Comment by DaronLord** [comment]
Sorry about the speculation.  That was me hoping it was simple.  I will test you new version whenever you say go.  Thanks.

**Comment by dustindclark** [comment]
Alright, give 0.1.7 a go.  You may get some unexpected behavior if you define commands for more than just on/off.  If you're just using on/off though, Siri will be able to control your devices by room.
